export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const HANDLE_SIGNUP_INPUT = 'HANDLE_SIGNUP_INPUT';
export const CLEAR_SIGNUP = 'CLEAR_SIGNUP';
export const SUBMIT_SIGNUP_FORM = 'SUBMIT_SIGNUP_FORM';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
